defaults:
  - _self_
  - dataloader: linear/default
  - wandb: default
  - fabric: single_gpu

exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir

  dataset_name: linear_spiral

  run_func: 
    _target_: experiment.generate_linear_system_dataset.run
