defaults:
  - _self_
  - dataloader: 
  - loss: reconstruction_mse
  - metric: 
  - models: 
  - wandb: default
  - fabric: single_gpu


exp:
  seed: 42
  log_dir: # set during runtime to automatically created dir

  run_func: 
    _target_: experiment.train_joined_gcn_moment_reconstruction.run

  run_id: ???